### ISSUE TITLE
setuptools warnings

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [facelessuser/wcmatch#184] opened 2022-05-18 13:30 UTC
```
 * QA Notice: setuptools warnings detected:
 * 
 * 	The license_file parameter is deprecated, use license_files instead.
 ```

**Comment by facelessuser** [comment] 2022-05-21 02:23
Closing this as a duplicate of #185

@gir-bot add S: duplicate

**Closed** 2022-05-21 02:23 UTC
Labels: S: duplicate, T: maintenance
