### ISSUE TITLE
Add option to support capturing

### ISSUE THREAD

**Issue by normanr** [facelessuser/wcmatch#132] opened 2020-08-11 21:12 UTC
Similar to extended match patterns: it would be nice to be able to be able to have a flag to enable selective capturing of matched text when using wcmatch.translate. This could probably be done with `(...)` so that it's similar to an extended match, but without any prefix. Existing match patterns are non-capturing and should probably stay as such. `@(...)` also makes sense as non-capturing if you think of the `@` like it's used in make files to suppress echoing of commands.

**Comment by facelessuser** [comment] 2020-08-11 22:07
This is an interesting suggestion. I'm not quite sure what direction to take with this.

Translate mainly exposes what we do internally. It was mainly publicly exposed to provide something similar to what Python does with the builtin fnmatch. Beyond that, it wasn't intended to take on features specific to itself, merely expose the internal patterns in case the user wanted to create reusable, precompiled patterns.

Generally, we try and follow Bash, though we deviate in two notable ways:

1. Allowing negate patterns via `!` at the start of a pattern via the `NEGATE` flag. Though the `NEGATE` flag allows the use of `-` instead.

2. Allowing patterns to be chained together with the `|` for a single string input via the `SPLIT` flag.

Both the above features came about due to necessity as we wanted to have a simplified single input for the [Rummage](https://github.com/facelessuser/Rummage) project, which caused me to write this library. We borrowed `!` from gitignore, and splitting via `|` seemed a logical solution.

`MINUSNEGATE` was originally added as I wasn't sure how I wanted to handle the case of `!(`. Is this an exclude pattern or the start of an extended negative glob pattern `!(...)`? I debated trying to parse it and backtracking if it failed to parse as an extended pattern, but ultimately settled on just checking if `(` was escaped. `MINUSNEGATE` could essentially be phased out if we desired.

This leads me to the complications that could be caused by a capturing group of `(...)`. While `@(...)` is part of Bash, `(...)` is not. Introducing such functionality would create a conflict with existing features. Currently, we can express that we want an exclude pattern that starts with brackets by doing this `!\(`. We can express an extended negative group with `!(`. By introducing this new capturing pattern these would be impossible to specify an exclude pattern with a capturing group `!(` (which is this 🤷). Sure, we can enable `MINUSNEGATE` and work around this with `-(`, but generally, I would prefer to not force a scenario that breaks combinations of features.

Also, this deviates from the goal of the project. Its sole purpose is simply to match files, and while it uses regular expressions to accomplish the task, it is not meant to be a tool to construct specialized regular expressions. Also, if we create capturing groups for `@()`, it leads to the questions of why not capturing groups for `+()`, `*()`, etc. Do we come up with a whole new set of special symbols for capturing variants? What if Bash introduces something in the future that we'd like to adopt but is incompatible?

This is my current way of thinking. I'm open to discussing this, but this at least helps to set the stage with my current thinking.

@gir-bot remove S: triage
@gir-bot add T: feature, S: needs-decision

**Comment by facelessuser** [comment] 2020-08-12 17:03
After thinking about this more, my current leaning is to not implement it:

- The library is geared towards file matching, filtering, and globbing. This is a regex specific request and doesn't actually lend to extending the actual file matching, filtering, or globbing.

- The purpose of translate is to expose the internal matching patterns, nothing more. Further altering of the pattern for complex path manipulation is really out of scope. Glob patterns are not regex, and shouldn't model regex in that sense, even if we use regex under the hood. I think I'd like to avoid going down that path. I don't mind changing the regex if it somehow enables improving current matching, filtering, and/or globbing behavior, but this request doesn't really seem to do that.

- The requested syntax will clash with existing features, and while we deviate a little from Bash, I'd like to not deviate too far preventing us from keeping parity in the future.

I'm not shutting down discussion, but as things stand right now, I'd like to avoid adding this feature as currently described.

@gir-bot remove S: needs-decision
@gir-bot add S: rejected

**Comment by normanr** [comment] 2020-08-12 20:11
Fair enough. I was thinking that `()` would only capture if there was no control in front of it. (I never wanted `@()`, `*()`, `+()`, etc to behave differently from each other). I don't think that addresses what would happen with `!(` though.

The glob libraries that do support capturing (eg: [pachyderm/ohmyglob](https://github.com/pachyderm/ohmyglob) [golang], [tailhook/capturing-glob](https://github.com/tailhook/capturing-glob) [rust]) either do it as `()` (if they don't support extglob), or just capture all the extglob groups (or more likely didn't think to use non-capturing groups). I was looking for a way to specify capturing vs non-capturing at the per-group level within the glob pattern.

My particular use-case is that there's an existing tool that matches with globs, and then creates a summary keyed by the glob used to match the files (roughly speaking). The complication comes from needing to specify how to match a number (of any length) as part of the filename. Eg: For files like: `'file1.hello.txt'`, `'file23.world.txt'`, `'glob4.matching.txt'` matched with `'@(file)+([[:digit:]])@(.*)'` (assuming that extglob pattern-lists are captured) would output `['file','1','.hello.txt']`, `['file','23','.world.txt']`. I would like to exclude the numeric part so that the output is `['file','.hello.txt']`, `['file','.world.txt']`). So I thought that adding per-extglob-pattern-list capture control might be a way to achieve that.

An alternate option might be to allow the extglob cardinality prefixes to also apply to ranges, so `+[[:digit:]]` would match a number, but wouldn't create a captured pattern-list. Then `'@(file)+[[:digit:]]@(.*)'` would match the files I'm interested in and the parts of the filename matched by the extglob pattern-lists would group as desired.

**Comment by facelessuser** [comment] 2020-08-12 20:34
I think, if we were to add such a feature, we'd have to create an interface specifically for capturing.

```
capture('file', 'patter()', exclude=['optional', 'exclude', 'patterns'], flags=0)
```

In that case, we would have to handle exclusion separately, or if using `NEGATE` with `EXTGLOB`, `MINUSNEGATE` would be required. Not sure which direction I would go in this case.

Capture though would be confusing if it accepted multiple patterns like everything else we do. You'd get a captured return, but have to verify what pattern it matched...what do you think?

My initial thought, if we did this, is that we wouldn't allow pattern expansions with `BRACE` or `SPLIT`, and it would only accept a single pattern, though you could use as many exclude patterns as you wanted as they never "match", they just exclude from matches.

**Comment by facelessuser** [comment] 2020-08-12 20:37
Yeah, if we went with separate `exclude` input, it would make `NEGATE` unnecessary. Considering this is a specialized match function, what is allowed in it would be different.

**Comment by facelessuser** [comment] 2020-08-12 20:40
I also don't know how this works in the other libraries you mentioned, but I'd be inclined to limit them the same way `EXTGLOB` limits them. This means they would not span path separators.

This would be okay:

```
some/(pattern)
```

This would not be okay:

```
(some/pattern)
```

I guess something like this would need to be discussed.

**Comment by facelessuser** [comment] 2020-08-12 20:45
Or maybe we don't allow exclude at all. One pattern period. You can count the result however you wish. No excludes means no conflicts.

**Comment by facelessuser** [comment] 2020-08-12 21:30
We may need to carefully track capturing groups. `REALPATH` won't allow us to descend into symlinked folders with `**` unless `FOLLOW` is enabled, so when we use things like `globmatch` with `REALPATH`, we already use capture groups to mark stuff matched by `**`, then we can double check the directories captured by `**` in `REALPATH` mode (if we are not enabling `FOLLOW`) whether any of those directories were symlinks.

We currently omit any `REALPATH` pattern changes from translate as the use of capturing groups is only for us internally when we are processing the paths in real path mode.

I guess if we are tracking which capture group we are adding that are for `**`, we can filter those out from the results...so maybe can still probably pull it off.

**Comment by normanr** [comment] 2020-08-13 18:01
oof, that's waay more than I would need/use. In my case the names don't exist locally (they're read from a file), and are all in a single folder (so `GLOBSTAR` doesn't come into effect). I think it would be fine to return the captured group with the pattern that matched it. I would basically replace
`if fnmatch.fnmatchcase(name, pattern): return pattern`
with
`cap = wcmatch.capture(name, pattern); if cap: return ''.join(cap)` (or similar, depending on the final API)
Doing it by directly using translate would be possible, but it would just be replicating the logic in capture, so it should just use capture if it's available.

Syntax-wise, I'm not sure if capturing, or range cardinality is more-or-less of a change. Capturing is at least something that other libraries do. I don't think I can say the same for range cardinality.

**Comment by facelessuser** [comment] 2020-08-13 22:22
You'll have to forgive me as when I think/talk about this, I'm thinking of the complexity of implementing this (based on how things are already implemented). So I'm thinking about the existing features I have to workaround. I also can't just consider it from one person's use case, I have to think about the implications of adding such a feature, and what other feature requests it may spawn.

I'm also not 100% sold on capturing yet, but I am exploring it. While others may offer it, nothing dictates that it must be supported here.

So, to simplify what I think it **could** look like (without talking about internal implementation):

## Potential Implementation

- Capture would take only one pattern, which differs from our other match/filter/glob functions as they can take a list of patterns or have a single pattern expanded internally via brace expansion etc. So capture would be considered to work on a singular pattern only.

- Since capture would work on only one pattern, there would be no exclusion filtering, so no `NEGATE` and related flags. Also, limiting this to one pattern means no `BRACE` or `SPLIT` which expands the pattern internally. Not really interested in users managing a matrix of capture groups 🙂.

So, some real rough exploritory code has yeilded this:

```py3
>>> pathlib.Path('docs/src/markdown/index.md').globcapture('docs/(src)/(*)/@(index)@(.md)', flags=pathlib.E | pathlib.REALPATH)
('docs/src/markdown/index.md', 'src', 'index', '.md')
```

This currently makes EXTGLOB patterns capture as well as `(...)`. Though there are still some issues as the way we handle `!(...)` makes us get duplicate capture patterns (notice the `None`):

```py3
>>> pathlib.Path('docs/src/markdown/index.md').globcapture('docs/(src)/(*)/!(not this)@(.md)', flags=pathlib.E | pathlib.REALPATH)
('docs/src/markdown/index.md', 'src', 'index', None, '.md')
```

We could also make it so EXTGLOB patterns don't capture, but I'd have to think about how workaround inverse groups. They are messy difficult to begin with (I found some small related bugs in this area just exploring this).

I'm also capturing the whole path as group 0 right now, that's probably unnecessary :shrug:. It just returns a simple tuple. No match object or anything like that.

I have no timeline on this, and no current promise that we are moving forward with this. I find the problem interesting, but I haven't made a decision. I fear by having this, the desire for a replacement with groups (much like regex) may come as a request as well. Maybe not from you, but potentially in the future, so I do have to think about what I am willing to maintain.

**Comment by facelessuser** [comment] 2020-08-13 23:40
I've resolved the duplicate capture issue with `!(...)`. I'd like to handle these cleaner one day, but it at least works now. So it seems viable.

```py
>>> from wcmatch import pathlib
>>> pathlib.Path('docs/src/markdown/index.md').globcapture('docs/(src)/(*)/!(not this)@(.md)', flags=pathlib.E | pathlib.REALPATH)
('docs/src/markdown/index.md', 'src', 'index', '.md')
```

Not sure whether we want to have EXTGLOB patterns capture, but 🤷.

**Comment by facelessuser** [comment] 2020-08-14 06:08
I think in the short term, I may just enable capturing groups for EXTGLOB patterns in translate.

Adding support for `(...)` is a bit redundant when we have `@(...)` which does the same thing. A user would simply enable `EXTGLOB`, and they will do the capturing.

We already know when we are handling a translate vs a normal globmatch, so we can use that as the trigger.

The reason we use non-capturing groups by default is for increased speed, but we can assume that if someone wants to use translate over the other API functions, that maybe they want a little more control, so I'm fine enabling captures for that. We'll let the user manage replaces and such with regex, and let them use that interface instead of exposing our own.

We never call translate directly, it is mainly a user function, so it won't impact us in any other way. And since we will make translate enable capturing groups as the new default, we shouldn't need a special flag for it. With the `!(...)` flag issue sorted, the rest is fairly trivial.

**Comment by facelessuser** [comment] 2020-08-14 06:27
Working example:

```py3
>>> gpat = glob.translate('@(file)+([[:digit:]])@(.*)', flags=glob.E)[0][0]
>>> pat = re.compile(gpat)
>>> pat.match('file1.hello.txt').groups()
('file', '1', '.hello.txt')
```

I guess it took me a bit to come around to basically what you asked for in the beginning, but better late than never. And now I don't have to add another flag, or muck with the syntax, so that is nice.

@gir-bot remove P: maybe

**Comment by facelessuser** [comment] 2020-08-14 06:36
Experimental branch: https://github.com/facelessuser/wcmatch/tree/feature/capture.

If you try it, let me know if you run into issues. I haven't written any unit tests for it yet and only basic testing. Probably won't get around to polishing up until some time next week.

**Comment by facelessuser** [comment] 2020-08-14 16:18
It occurred to me that it was probably desired that things like `+([[:digit:]])` was desired to match all digits, not just the last captured group (like regex does), so I adjusted logic to just wrap the non-capturing group with a capturing one: `((?:[[:digit:]])+)`. I think that is more in line for what people may desire. That will keep you from having to double wrap groups: `@(+([[:digit:]]))`.

I opened a pull as I've now added tests and documentation to cover the new addition. Just let me know if what I have there works for you or if you have additional suggestions.

**Comment by normanr** [comment] 2020-08-14 21:42
I actually don't want to match the digits at all. I'm trying to get a result of: ('file', '.hello.txt').

**Comment by facelessuser** [comment] 2020-08-14 21:51
Regardless of whether you want to capture numbers or not, what do you think of the behavior?

**Comment by facelessuser** [comment] 2020-08-14 21:52
It models the behavior of I think the first package you referenced, minus the redundant syntax.

**Comment by normanr** [comment] 2020-08-15 04:43
I like the idea of only triggering it for translate so that other operations are faster.

Good catch on repeated captures. I assume it applies to `*` and `+` alike, and not just for ranges, so something like `*(foo|bar)` would be translated to `((?:foo|bar)*)`

**Comment by facelessuser** [comment] 2020-08-15 05:04
Yes, `*(foo|bar)` would translate to `((?:foo|bar)*)`. Same with `+(...)`, `?(...)`, etc.

Basically, everything matches and works like it always has, we just construct the same pattern with the capture groups and let the user sort out what (if anything) they want to do with those groups.

I think it is a decent compromise as I don't have to sacrifice the current syntax (or muddy the waters of the syntax) with our own custom syntax and I don't have to implement a new capture API. All I have to do is just expose captures on the EXTGLOB patterns, which are already a great mirror of the regex capture groups. It costs me very little.

I think the deviation from how regex captures with `()+` and how we capture with `+()` makes sense in how users are most likely going to use it. At least that is my opinion so far 🙂.

**Comment by normanr** [comment] 2020-08-15 15:15
[pachyderm/ohmyglob](https://github.com/pachyderm/ohmyglob) does the same thing for it's captures (not for `@()` as it's unnecessary), so sounds fine to me.

**Comment by facelessuser** [comment] 2020-08-15 15:22
Yup, we `@()` is unnecessary, and `!()` actually wraps the `.*` (or whatever we use, but you get the idea) after the exclusion part.

**Comment by facelessuser** [comment] 2020-08-15 15:35
From what I could tell, `pachyderm/ohmyglob` and `tailhook/capturing-glob` are literally the only glob capturing libraries, so they are outliers really, but I think this is probably a fine addition to add as it doesn't hurt any existing features and doesn't cost us much to add...at least as long as we never move away from generating full path regex internally for path matching. On the plus side, me digging into this area helped expose some more `!(...)` issues which are now fixed, so win, win.

**Comment by facelessuser** [comment] 2020-08-16 14:06
Capturing will be in the next release, whenever that gets released.

**Closed** 2020-08-16 14:06 UTC
Labels: T: feature

**Comment by normanr** [comment] 2020-08-17 04:16
[miracle2k/python-glob2](https://github.com/miracle2k/python-glob2) captures too. It only captures patterns though, so it's not particularly flexible.

**Comment by facelessuser** [comment] 2020-08-17 04:53
Ah, wasn't aware that glob2 did captures of any kind.
