### ISSUE TITLE
Differences from other programming languages, such as golang, php 

### ISSUE THREAD

**Issue by techoner** [facelessuser/wcmatch#175] opened 2021-05-08 05:41 UTC
In PHP
```
fnmatch( "*/foo", "/foo" , FNM_PATHNAME | FNM_PERIOD) ; // true
```
In Go
```
path.Match("*/foo", "/foo") // true
```
But using wcmatch :
```
pathlib.PurePath("/foo").match("*/foo")  // False
```

**Comment by facelessuser** [comment] 2021-05-08 05:55
@techoner Here I am in Bash. I am at the location `/` (the root).

```console
$ ls
Applications	Volumes		etc		sbin
Library		bin		home		tmp
System		cores		opt		usr
Users		dev		private		var
$ echo */bin
usr/bin
```

As we see above, glob does not match `/bin`, but it does match `/usr/bin`.

I am targetting Bash style matching. I even mention that "Globmatch matches what glob globs", and as we can see above, `glob` would not match `/bin`, so `globmatch` will not match `/bin`.

Just because others do something wrong, doesn't mean we need to. I'm open to an argument as to why it should match in this case, but I will need something a bit more than "others do it".

Regardless of what other libraries may do, this doesn't make sense to me:

```go
path.Match("*/foo", "/foo") // true
```

What is `*` matching in this case? There is nothing there, but somehow it is capturing a non-existent directory? And then matching the `/foo`?

**Comment by facelessuser** [comment] 2021-05-08 06:22
I'm at least not alone in this thinking. In JavaScript:

```js
Welcome to Node.js v15.14.0.
Type ".help" for more information.
> var minimatch = require("minimatch")
undefined
> minimatch("/foo", "*/foo")
false
```

**Comment by techoner** [comment] 2021-05-08 06:38
@facelessuser I use `fnmatch` in C language, and the result is the same :
```
#include<stdio.h>
#include<stdlib.h>
#include <fnmatch.h>
int main()
{    
    int ret;
    ret = fnmatch("*/foo","/foo", FNM_PATHNAME | FNM_PERIOD);   // 0, matched
    printf("fnmatch ret = %d\n", ret);
    exit(0);
}
```

**Comment by facelessuser** [comment] 2021-05-08 06:43
I can probably hunt down other libraries that do it like we do as well, but I'm still looking for an answer as to why you think what PHP, Go, and C do are correct and we are wrong?

Also, what is `*` matching in this case? Based on the rules of the pattern, the match doesn't make sense.

**Comment by techoner** [comment] 2021-05-08 06:51
Well, I just want to find a cross-language `GlobMatch` library .

**Comment by facelessuser** [comment] 2021-05-08 07:10
It is very likely that all languages have some slight quirks that make them sightly different. Or have features that others do not.

In order for me to make such a change, I would need a clear argument that makes a good case for why the change is better. Simply matching others just because they do it is not something I want to do.

The only thing I can think of is that they are approaching it as if the they are removed from the filesystem and maybe `*` is matching the unnamed root.

We currently require absolute paths to be matched with absolute patterns, and relative paths to be matched with relative patterns. I'm not sure I follow this relative matching of an absolute path.

It's late here, I'll have to think about this more.

**Comment by facelessuser** [comment] 2021-05-08 18:44
I've thought about this, and here is what I think the problem is and why I am hesitant to add such behavior. Let's take the Go implementation as an example. All these match the given patterns and yeild `true`:

```go
package main

import (
	"fmt"
	"path/filepath"
)

func main() {
	fmt.Println(filepath.Match("*/foo", "/foo")) // true
	fmt.Println(filepath.Match("a/*/b", "a//b")) // true
	fmt.Println(filepath.Match("*", "")) // true
}
```

To me, these don't make sense, but I get why people implement it to return `true`. They make the argument that `*` is stated as matching zero or more characters, so, if you take this strictly, you could argue that all these cases _should_ match. This is the entire basis for doing what you see above (or at least what I believe most would argue).

But let's take `a//b` as an example. We are going to argue that `a/*/b` should match here based solely on the statement that `*` matches zero or more chars. But we all know that `a//b` normalizes to `a/b` as there is no directory with an empty name. `a/*/b` would never match `a/b`, but that is actually what `a//b` represents. `glob` will never crawl your system and return a path of `a//b`. That path doesn't exist. As a matter of fact, often shells will intuitively normalize `a//b` internally to `a/b`.

My point is simply that while `*` technically matches zero or more characters, the file pattern contained between the slashes (`/*/`), where `*` is the entire pattern, must match an actual file or directory. If no file is matched, can you really argue that it has matched a file or directory?

I think this is where people get wrapped up in the exact wording and code to the exact letter of the law without taking into consideration what is actually desired.

I never want `*` matching an empty string. An empty string is not a file or directory, it is nothing!

Let's say a user inserts an extra slash by mistake and gives me `a//b` and the pattern `a/*/b` and this matches, this could match an unintended folder or file. Let's say they are deleting folders with this pattern. This is a BIG problem, regardless of whether someone can argue that "technically" it is correct. `a/*/b` should match all `b` files/folders under any child folder of `a`, but it should not match the direct child `b`. For this reason, I also view `*/foo` matching `/foo` also quite incorrect, regardless of how many implementations swear this is the "correct" way to do it. In reality `glob` will never return match and return such a path, so why should file path matcher match such a path?

In short, yes `*` matches zero or more characters, but the entire file pattern (between slashes) must match a valid file or folder, by definition! The one exception is `**` which matches zero or more folders, not characters. So in its very definition, it is clear that it does not have to match a file or folder. In this case, it will match:

```py
>>> glob.globmatch('/foo', '**/foo', flags=glob.G)
True
```

If you need to match both `<some folder>/foo` **and** `/foo`, then feed in both patterns:

```py
>>> glob.globmatch('/foo', ['*/foo', '/foo'])
True
```

I personally think I am providing a sound argument and sound logic that I would be willing to argue with just about anyone 🙂, regardless of how "correct" they may argue their implementation is. I would gladly sit in the crowd of less "correct" and argue that what we do is more predictable and safer than any implementation that does it "correctly" (assuming that their interpretation is the official "correct" interpretation).

I hope this all makes sense, and I hope you find it to be a satisfying answer. I know this may not give you what you were hoping for (an implementation that matches all other implementations) but I would need a very strong argument to probably change my mind on this, unfortunately, references to other implementations that do it just because "`*` technically matches zero or more characters" does not seem like a strong argument.

**Comment by facelessuser** [comment] 2021-05-09 15:42
Closing as there is no current actionable item.

I am open to further discussion, assuming some new points can be brought to the table that hasn't already been addressed. Feel free to reopen if there is further discussion to be had.

**Closed by facelessuser** 2021-05-09 15:42 UTC
Labels: S: wontfix

**Comment by facelessuser** [comment] 2021-05-18 15:51
I wanted to post this here just as a reference for anyone else stumbling upon this issue in the future:

Referencing the fnmatch library: https://man7.org/linux/man-pages/man3/fnmatch.3.html

```
       FNM_PATHNAME
              If this flag is set, match a slash in string only with a
              slash in pattern and not by an asterisk (*) or a question
              mark (?) metacharacter, nor by a bracket expression ([])
              containing a slash.
```

`fnmatch` calls that use `FNM_PATHNAME` basically use the same simple file name matching except that special characters and sequences (`?`, `*`, `[]`) will not match `/`. `fnmatch` has no context to determine that there are individual files in the name that it is matching, just some very rough `/` logic on top of normal file name matching. That's it. This is pretty naive and only an approximation of something like `globmatch`, but not equivalent.

`fnmatch` + `FNM_PATHNAME` is simply not intelligent enough to handle a directory path 100% proper. But for a lot of people, it is "good enough". If a library's aim is simply to replicate `fnmatch` with the path flag, this is what they should do. This was not our aim. We wanted to replicate true glob matching. This is why we don't simply have a flag in `fnmatch` that adds separator logic but have an entirely different function called `globmatch`.

So these are the differences (at least the ones off the top of my head):

1. Glob was not designed for the Windows file system, so it has no concept of Windows drives, so we adapted it. Windows drives are not matched with wildcards, you have to explicitly define your windows drive as glob patterns are relative to a specific drive. If you need to specify a specific drive, you must explicitly specify that drive.

    On Linux and macOS, there is no concept of different drives, they are all mounted under `/`, so everything is relative to `/`.

2. Windows doesn't distinguish between `/` and `\` and forbids either of these in file names. Our `fnmatch`, as well as `globmatch`, treat these the same (as long as `\` is escaped: `\\`). In `globmatch` these aren't just matching the character, but are matching path separators with additional path separator logic. When a separator is encountered, the pattern between the separators must match a file; therefore, `*`, if it is the entire pattern between the separators, must match a file. Below, bash just returns the pattern as it could not match a file. We just don't return a file.

    ```console
    bash-5.0$ echo docs/*/src
	docs/*/src
    ```

	```py
    >>> from wcmatch import glob
    >>> glob.glob('docs/*/src')
    []
    >>> glob.globmatch('docs//src', 'docs/*/src')
	False
    ```

2. If there is no pattern between separators, the separators are collapsed to one and they will match one or more path separators. File systems will internally collapse consecutive slashes for files. Glob will still match the same file, no matter how many consecutive slashes you provide, the only difference is that it returns the files with the same number of slashes. We don't currently retain the extra slashes in the return like bash as these aren't helpful in any way. We could, but it doesn't really add anything useful. The different variants are still matching the same files.

	```console
    bash-5.0$ echo docs//*
	docs//src docs//theme
    bash-5.0$ echo docs/*
    docs/src docs/theme
    ```

    ```py
    >>> glob.glob('docs//*')
    ['docs/theme', 'docs/src']
    >>> glob.glob('docs/src')
    ['docs/src', 'docs/theme']
    >>> glob.globmatch('docs/src', 'docs//*')
    True
    >>> glob.globmatch('docs//src', 'docs/*')
    True
    ```

    For this reason, our `globmatch` will treat consecutive separators as one and will have them match one or more separators, essentially normalizing them and the results.

This should help define how and why `globmatch` differs from `fnmatch` + `FNM_PATHNAME`. Whatever "standard" we are assuming `globmatch` should adhere to, we should remember that `globmatch`'s aim is different than implementations that use `fnmatch` + `FNM_PATHNAME` as their file directory matching reference. We use `glob` as our reference.
