### ISSUE TITLE
Add support to translate to a limited POSIX regex for use in PostgreSQL (and Django)

### ISSUE THREAD

**Issue by pombredanne** [facelessuser/wcmatch#209] opened 2023-10-31 09:41 UTC
It would be super useful enhancement to have a way to translate to the limited POSIX regex that DBs support (as well as sed/grep) as well as to the Python regex syntax.

See https://docs.djangoproject.com/en/4.2/ref/models/querysets/#regex 

For PostgreSQL this would be: https://www.postgresql.org/docs/current/functions-matching.html#FUNCTIONS-POSIX-REGEXP

This is because of https://github.com/nexB/scancode.io/issues/960

**Comment by facelessuser** [comment] 2023-10-31 11:48
Help me out. Instead of having me search into different threads and links can you clearly explain what the issue is? Tell me what part of the syntax you are having trouble with and what your proposal is. Once clearly explained, I can evaluate if accommodations are appropriate/possible or not.

**Comment by facelessuser** [comment] 2023-11-03 13:10
@pombredanne While I am open to considering changes, I do need you to provide a proposal for what changes you are asking for. If none are provided, I will have to close the issue. Thanks!

**Comment by facelessuser** [comment] 2023-11-07 15:57
@pombredanne I'll give this until the end of the week for the requested information. If no response is provided by the end of the week, I will assume this issue stale and will close.

**Comment by facelessuser** [comment] 2023-11-10 16:32
As there has been no engagement  in this issue to provide the requested information, I am considering this issue stale and will close accordingly.

**Closed** 2023-11-10 16:32 UTC
Labels: S: invalid, S: more-info-needed, S: triage
