### ISSUE TITLE
glob.glob fails on absolute paths

### ISSUE THREAD

**Issue by Dylan-Brotherston** [facelessuser/wcmatch#173] opened 2021-03-14 04:12 UTC
Shell globing can accept an absolute path:
```shell
$ echo /path/to/dir/file_*.ext
/path/to/dir/file_name.ext
```
and the entire path is returned.

---

`python3 glob.glob` matches this behaviour:
```python
>>> from glob import glob
>>> glob("/path/to/dir/file_*.ext")
['/path/to/dir/file_name.ext']
```

---

`wcmatch.glob.glob` doesn't match this behaviour: instead returning nothing.
```python
>>> from wcmatch.glob import glob
>>> glob("/path/to/dir/file_*.ext")
[]
```

---

This can be worked around with `root_dir=...` or `chdir()`.
But then only the basename is returned not the full path, and extra steps must be taken to reintroduce this component.
```python
>>> glob("file_*.ext", root_dir="/path/to/dir/")
['file_name.ext']

>>> chdir("/path/to/dir/")
>>> glob("file_*.ext")
['file_name.ext']
```

---

Ideally `wcmatch.glob.glob` would match the behaviour of `shell` and `python3 glob.glob`
```python
>>> from wcmatch.glob import glob
>>> glob("/path/to/dir/file_*.ext")
['/path/to/dir/file_name.ext']
```

**Comment by facelessuser** [comment] 2021-03-14 04:17
@Dylan-Brotherston I need more info. Wcmatch to start?

Also, here is wcmatch using absolute paths:

```py
>>> from wcmatch import glob
>>> glob.glob('/Users/facelessuser/Code/github/wcmatch/*.py')
['/Users/facelessuser/Code/github/wcmatch/setup.py']
```

So I'm not sure what you are showing me with it not working as it does in fact work for me. Is there something else going on? Something specific with your environment?

**Comment by Dylan-Brotherston** [comment] 2021-03-14 04:26
This is `python3.7.3` Wcmatch version `8.1.2`

Given was the exact output for a bash shell and a python shell.
```python
>>> import os.path
>>> os.path.exists('/path/to/dir/file_name.ext')
True
>>> from glob import glob
>>> glob("/path/to/dir/file_*.ext")
['/path/to/dir/file_name.ext']
>>> from wcmatch.glob import glob as GLOB
>>> GLOB("/path/to/dir/file_*.ext")
[]
>>> os.path.exists('/path/to/dir/file_name.ext')
True
```

Even if there was something non-standard about my environment (i don't think there is) I would expect everything or nothing to fail.

**Comment by facelessuser** [comment] 2021-03-14 04:30
@gir-bot add S: more-info-needed

Considering that our tests actually test absolute paths, I'm suspecting there is something locally that is missing from this bug report. I've tried the same thing and have no issues:

```py
>>> import os.path
>>> os.path.exists('/Users/facelessuser/file_name.ext')
True
>>> from wcmatch.glob import glob
>>> glob('/Users/facelessuser/file_*.ext')
['/Users/facelessuser/file_name.ext']
```

This is the latest `wcmatch`, Python 3.9.1.

**Comment by Dylan-Brotherston** [comment] 2021-03-14 04:32
Correction, there is something non-standard about my environment.
`/home/` directories are automounted from a fileserver.
```python
>>> from wcmatch.glob import glob
>>>glob("/home/USER/path/to/dir/file_*.ext")
[]
>>> glob("'/tmp_amd/SERVER/export/SERVER/USER/path/to/dir/file_*.ext'")
['/tmp_amd/SERVER/export/SERVER/USER/path/to/dir/file_name.ext']
```
But this isn't an issue with the automounter itself as regular python libraries can find the file.

**Comment by facelessuser** [comment] 2021-03-14 04:35
Help me out here. How do I reproduce your issue? There is no flaw in the pattern logic, it has been shown that absolute paths work. So it seems you have some "automounter" thing going on, but I don't know how to debug this as I'm not sure what steps I can take to replicate this.

**Comment by facelessuser** [comment] 2021-03-14 04:56
I do find this issue intriguing. I'm very interested in what fundamentally is different about accessing `/home/USER` vs `/tmp_amd/SERVER/export/SERVER/USER`. While a simple `os.path.exists` may show that Python can see it, something appears to not behave quite like a normal path, as similar tests show `/tmp_amd/SERVER/export/SERVER/USER` works just fine.

**Comment by Dylan-Brotherston** [comment] 2021-03-14 05:41
I'll try to provide as much information as I can but it will be through my own experiments and correspondence with the server admin.

The only bit of trivia that I can provide right now is that non-interactive SSH doesn't trigger the automounter, apart from thay I haven't seen another issue like this.

**Comment by facelessuser** [comment] 2021-03-14 06:59
It may be something that must be debugged on your side. At the very least to figure out what we are doing that doesn't work.

It doesn't sound like it is a problem with accessing the folder as providing `root_dir` works. And keep in mind, when you are passing in `root_dir`, wcmatch is **not** changing the directory.

Because `wcmatch` can simulate case sensitive matching and vice versa, maybe this is where the problem comes in as we crawl through all the folders in the absolute path, and maybe it is having trouble with your automount path because it doesn't actually behave right when we do more than just check if it exists.

Consider this, I'm on a mac, and with Python's glob, it gets confused because, for some reason, it thinks that macs are case sensitive, but they are not by default, so they do lazy `exists` checks until you do a magic pattern, and then they get it wrong. Notice the last one doesn't match.

```py
>>> import glob
>>> glob.glob('/Users/facelessuser/globtest/CASE')
['/Users/facelessuser/globtest/CASE']
>>> glob.glob('/Users/facelessuser/globtest/case')
['/Users/facelessuser/globtest/case']
>>> glob.glob('/Users/facelessuser/globtest/c*')
[]
```

So, Python allows the OS to tell it whether the folder exists when a literal name is used, and the OS is saying, "hey, I don't care about case", but when a magic pattern is used, Python goes "Oh, I know you are case sensitive", and it gets it wrong. Now, yeah, you can enable case sensitivity on a mac, so it isn't always wrong, but generally, for the average user, it is these days.

With `wcmatch` this isn't a problem as you can tell it you want case insensitive matching:

```py
>>> from wcmatch import glob
>>> glob.glob('/Users/facelessuser/globtest/CASE', flags=glob.I)
['/Users/facelessuser/globtest/CASE']
>>> glob.glob('/Users/facelessuser/globtest/case', flags=glob.I)
['/Users/facelessuser/globtest/CASE']
>>> glob.glob('/Users/facelessuser/globtest/c*', flags=glob.I)
['/Users/facelessuser/globtest/CASE']
```

To do this, we will see what the OS returns for the children under each folder and see if it returns the file name that we expect, then we can make a choice to match a literal name with case sensitive logic or insensitive logic. This might be where we are getting hung up in your case. Maybe as we are asking the directories under `/home/USER/path/to/dir`, they aren't returning the folders we expect. When you use `root_dir`, we ignore all of that and assume `root_dir` is correct if it exists. In this case, `root_dir` is treated with just the simple "do you exist" logic as it isn't really part of the glob pattern. We don't change to it, but it gives you the same feeling.

If I had to guess, the issue is with us crawling those "root" folders, and they aren't behaving like real folders.

**Comment by facelessuser** [comment] 2021-03-14 13:48
I was thinking about this problem this morning, does the built-in Python glob have a problem if you force the root dir to be crawled by making them magic?

```py
>>> from glob import glob
>>> glob("/[p]ath/[t]o/[d]ir/file_*.ext")
['/path/to/dir/file_name.ext']
```

I imagine this will at least make Python glob evaluate each folder more like `wcmatch` does. I'm curious if this exposes the issue in Python's default glob, or if there is something more.

**Comment by Dylan-Brotherston** [comment] 2021-03-15 06:48
So this issue is that `/home/` is actually empty:

```sh
$ ls /home
```

But trying to access a home directory will automagically work:

```sh
$ test -d /home/USER && echo True
True
```

---

Python `glob.glob` will immediately openat() the longest path without glob syntax:

```sh
$ strace -e trace=file python3 -c 'import glob; print(glob.glob("/home/USER/path/to/file_*.ext"))'
openat(AT_FDCWD, "/home/USER/path/to", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
lstat("/home/USER/path/to/file_name.ext", {st_mode=S_IFREG|0640, st_size=1064654, ...}) = 0
['/home/USER/path/to/file_name.ext']

$ strace -e trace=file python3 -c 'import glob; print(glob.glob("/home/USER/[Pp]ath/[Tt]o/file_*.ext"))'
openat(AT_FDCWD, "/home/USER", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/home/USER/path", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/home/USER/path/to", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
lstat("/home/USER/path/to/file_name.ext", {st_mode=S_IFREG|0640, st_size=1064654, ...}) = 0
['/home/USER/path/to/file_name.ext']
```

And will indeed fail if `home` or `USER` require globing

```sh
$ strace -e trace=file python3 -c 'import glob; print(glob.glob("/home/[Uu]SER/[Pp]ath/[Tt]o/file_*.ext"))'
openat(AT_FDCWD, "/home", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
[]
```

---

wcmatch will always start with an lstat() at `/` and work its way up.

```sh
$ strace -e trace=file python3 -c 'from wcmatch import glob; print(glob.glob("/home/USER/path/to/file_*.ext"))'
lstat("/", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
openat(AT_FDCWD, "/", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
stat("/HOME", {st_mode=S_IFDIR|0555, st_size=512, ...}) = 0
stat("/srvr", {st_mode=S_IFDIR|0755, st_size=36864, ...}) = 0
stat("/run", {st_mode=S_IFDIR|0755, st_size=580, ...}) = 0
openat(AT_FDCWD, "/home", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
[]
```

wcmatch doesn't have the ability to alter this behavior, even when glob.I and glob.U are given.

---

*Note: `strace` output cut for readability.*

**Comment by facelessuser** [comment] 2021-03-15 07:22
> And will indeed fail if `home` or `USER` require globing

This is the big thing I wanted to confirm. So, it looks like my hunch is correct. We at least know what the issue is now.

In light of this new information, I am kind of standing by my original assessment that `wcmatch` is not broken. And if we were to argue it is broken, Python's `glob` is broken as well, it just doesn't expose the issue quite so readily. This "automagically" stuff is impossible for either to really figure out.

> wcmatch doesn't have the ability to alter this behavior, even when glob.I and glob.U are given.

Yes, because we don't know if the file system is actually insensitive or not, which is why we do what we do, and why we get generally more consistent results. `glob.I` and `glob.U` just forces the logic one way or the other, but even without those flags, `wcmatch` is doing one of them, it is just dependent on the OS assumptions instead of the user's preference. As you've pointed out, `home` is empty, so there is some magic going on here that I think is a bit unrealistic to expect `glob` or `wcmatch.glob` to get right.

Even if we shortcut straight to the first magic pattern, it doesn't fix the problem, it just masks it. And, you can shortcut it with `root_dir` if necessary.

I don't know, I'm open to suggestions if you have any, but I'm not sure shortcutting to the first magic pattern is the answer. It would make case matching less reliable just to hide the reality that we are globbing a path that isn't really a path.

**Comment by Dylan-Brotherston** [comment] 2021-03-15 08:43
I agree that wcmatch is working as intended, and intuitively (the file system is unintuitive). 

Shortcutting to the first magic pattern should be valid if glob.C (and glob.U (?)) is given (as this would ensure the same logic as a standard shell glob).

I agree that an easier, and better, solution is to use `root_dir`.

An option to prepend `root_dir` onto each returned path would be ideal, as its not ideal to wrap glob() in a map().

Eg my usecase is:
```
fileinput.unput(files=glob())
```
And using `root_dir` requires a map() to be inserted.

**Comment by facelessuser** [comment] 2021-03-15 12:54
Yeah, this can still be done though:

```py
>>> from wcmatch import glob
>>> root_dir = '/Users/facelessuser/code/github/wcmatch'
>>> list(map(lambda x: os.path.join(root_dir, x), glob.glob('*.md', root_dir=root_dir)))
['/Users/facelessuser/code/github/wcmatch/LICENSE.md', '/Users/facelessuser/code/github/wcmatch/README.md']
```

Is that a little cumbersome to enter as an input? Sure. You can probably do it on a separate line instead of doing that inline, or wrap the logic in a function if you prefer.

Why not do `map` inside glob? Well, `root_dir` accepts a string or a file descriptor for the folder, it is not so easy to get a path from a file descriptor 🙃. You can do it, but the only way I've found so far is to `chdir` to the file descriptor, and then get `getcwd`. Not ideal.

Additionally, one of the reasons to use `root_dir` is to not get the `root_dir` in the path. I know this is in conflict with what you are doing though. You have to use `root_dir`, but then when you do, you want the `root_dir` appended. Probably just mapping beforehand or wrapping that logic in a function is going to be the best way right now.

I wish there was a cleaner way to handle your file system issue so it would just do what you expect. Unfortunately, you have a very non-standard scenario. If I ever run into such an issue myself (where I can debug it further), and am able to figure something out, I'd be happy to include a patch, but I suspect there probably isn't a clean way to handle it.

**Comment by facelessuser** [comment] 2021-03-15 14:17
I'm sorry, I'm confusing features. We have not added `dir_fd` yet. You can use a pathlib or string, but not a `dir_fd`. Regardless, one of the big things is that using `root_dir` should not append it, so I still don't think this is something we should do. It's not too difficult to do it externally either.

**Comment by facelessuser** [comment] 2021-03-17 21:18
Well, I think the general summary is that this is a quirky file system scenario and currently, wcmatch is doing what it is supposed to do. With that said, there are workarounds as discussed. Currently, there is no actionable item to us as `root_dir` is supposed to feel the same as changing the working directory.

Resolving issue with no action.

**Closed by facelessuser** 2021-03-17 21:18 UTC
Labels: S: more-info-needed, S: triage
